### ISSUE TITLE
Website Zoom Issue

### ISSUE THREAD

**Issue by Luke-Patterson1097** [hpvdt/website#16]
On Safari and other Apple products, we had encountered an issue where if you zoom the website out, it causes white bars/space to appear on the sides. I can't replicate this issue on my Windows PC, but we were able to do it on a Mac. I'm not sure if it currently exists or not, but this should be checked.

**Comment by savob** [comment]
Heyt @JadenStanshall  you have a Mac, can you please try this out?

**Comment by JadenStanshall** [comment]
No big deal, seems to be a common thing between all webpages opened in safari. The white space around the boarder is visible only when zooming out immediately after zooming in, but the page expands to fill the white space (back to normal) as soon as the zoom is released.
