### ISSUE TITLE
Team Members Page

### ISSUE THREAD

**Issue by Luke-Patterson1097** [hpvdt/website#18]
This page either needs a full update or needs to be deprecated. Will be up to the new webmasters what to do with it.

**Comment by savob** [comment]
IMO it feels a bit odd to do current members since it changes semi-regularly. 

I think it might be nice for us to list people that have made contributions to the team in the past as a way of having proof of what they did, should they ever need to prove it for a job or something.

**Comment by savob** [comment]
As per discussion today, have a separate "Current Members" and "Alumni" sections. Captain will provide active member lists when needed for updates going forward.

**Comment by savob** [comment]
Need updated member list from @captain-hpvdt
