### ISSUE TITLE
Remove the previous sponsors

### ISSUE THREAD

**Issue by Luke-Patterson1097** [hpvdt/website#19]
There's no point in having them on the sponsors page. I think all previous sponsors should be removed, or at least commented out in the .html pages.

**Comment by savob** [comment]
Yeah I second this, if they aren't actively sponsoring us I don't see why we should put them up forever. This is something to take up with the captain and finance exec.

**Comment by savob** [comment]
As per discussion with team, remove any and all former sponsors. If they aren't supporting us currently, then don't have them up there.
