### ISSUE TITLE
Add Sponsors

### ISSUE THREAD

**Issue by Luke-Patterson1097** [hpvdt/website#20]
CermanicSpeed and J. Roberts need to be added. Current sponsors should be double checked as well. There may be more outstanding sponsors that need to be added as well (Savo: some PCB related ones?)

**Comment by GeorgeWangnottaken** [comment]
#27

**Comment by savob** [comment]
Hey, are all our present sponsors properly reflected on the site now @Luke-Patterson1097 / @cool-sexy-guy-100 ? If so I would like to close this issue.

**Comment by GeorgeWangnottaken** [comment]
matches luke's list :)
