### ISSUE TITLE
Shared header and footer files

### ISSUE THREAD

**Issue by savob** [hpvdt/website#22]
Currently the header and footer need to be individually maintained page to page, e.g. updating the year and who updated the page. This can and currently does lead us to have inconsistent formatting and information across our pages.

We should look to use some sort of system where we can define the header and footer of our website in one place that is then referred to by our pages. There must be a way to do this using the website builder.

**Comment by savob** [comment]
So you're going to attempt this @GeorgeWangnottaken ?

**Comment by GeorgeWangnottaken** [comment]
yeah I should! I knew a lot less website stuff when I last tried this and when I marked this as wontfix, I forgot how helpful and nice having both a shared header or footer would be

it's not my first priority but i would like to close or fix this in august

**Comment by savob** [comment]
Not actually completed

**Comment by savob** [comment]
@GeorgeWangnottaken do we want to pursue this anymore or not? If not we should either close this "issue" or tag it as "won't fix".
